### ISSUE TITLE
Merged header cells creating separate tables 

### ISSUE THREAD

**Issue by HDTS-user** [ChrisPappalardo/eparse#1] opened 2023-12-26 05:57 UTC
When parsing a table with merged headers, the columns with the merged headers (left most) are being returned as separate tables.

e.g. for excel sheet with table
![image](https://github.com/ChrisPappalardo/eparse/assets/120087462/b6ae6d04-7b58-47ce-9e9d-945fd2ac924a)

executing
tables =  [table for table in get_df_from_file('test.xlsx')]

print(tables[0])
>>
(         3
1  Merged1
2     Col3
3        2
4        3
5        4
6        5
7        6
8        7, 'D2', 'Merged1', 'Sheet1')

print(tables[1])
>>
(         5
1  Merged2
2     Col5
3        4
4        5
5        6
6        7
7        8
8        9, 'F2', 'Merged2', 'Sheet1')

print(tables[2])
>>
(      1     2     3     4     5     6
2  Col1  Col2  Col3  Col4  Col5  Col6
3     a     1     2     3     4     5
4     b     2     3     4     5     6
5     c     3     4     5     6     7
6     d     4     5     6     7     8
7     e     5     6     7     8     9
8     f     6     7     8     9    10, 'B3', 'Col1', 'Sheet1')

**Comment by ChrisPappalardo** [comment] 2023-12-26 16:41
Hi, thanks for opening an issue.  This is intended functionality using the default loose setting (True), coupled with eparse being "greedy" - which means it will find all possible tables, including overlapping ones.  You can deal with this one of two ways.  First, you can set loose to False, which isolates the table I believe you are wanting to find in your example:

![image](https://github.com/ChrisPappalardo/eparse/assets/3485539/1bfb16d0-e39d-4877-b117-5419a18c0708)

The other thing you can do is to filter the row output on the columns you are expecting to find, in other words ignore this:

![image](https://github.com/ChrisPappalardo/eparse/assets/3485539/60230d89-75b3-41dd-aebb-cd3b930befcd)

And instead select this:

![image](https://github.com/ChrisPappalardo/eparse/assets/3485539/fb54a016-fc59-464e-910f-423486e6da2c)

Hope that helps.  Closing this ticket as it is not a bug.

**Closed as completed by ChrisPappalardo** 2023-12-26 16:41 UTC
